version: "3"
services:
  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  
  
  nats:
    image: nats
    container_name: nats
    command: -js
    ports:
      - 4222:4222
      - 8222:8222  # management
  
  
    # https://semgrep.dev/r?q=yaml.docker-compose.security.no-new-privileges.no-new-privileges
    security_opt:
      - no-new-privileges:true
